#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap us &
xrandr --output DP-2 --primary --mode 1920x1080 --rate 165 --rotate normal --output DP-0 --mode 1920x1080 --rate 75 --rotate normal --above DP-2 --output HDMI-0 --mode 1920x1080 --rate 75 --rotate left --left-of DP-0 &
picom &
polybar

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
